config/routes.rb
require 'sidekiq/web'

CompaignTw::Application.routes.draw do

  sidekiq_constraints = lambda{ |req| req.env['warden'].authenticate!({ :scope => :user }) }
  constraints sidekiq_constraints do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/users/auth/:provider/callback', :to => "users/omniauth_callbacks#callback"
  match '/users/auth/failure' => "users/omniauth_callbacks#failure", :as => :auth_failure

  Setting.providers.each do |provider|
    match "/users/auth/#{provider}", :as => "user_auth_#{provider}"
  end
  devise_for :users

  root :to => 'categories#index'
  resources :categories
  resources :petitions do
    resources :timelines
    post :sign, :on => :member
    get :dashboard, :on => :member
    resources :comments, :only => [ :index, :create ]
    resources :petition_mail, :only => [ :create ]
  end
  resources :users do
    resources :petitions do
      collection do
        match '/created' => 'users#created', :as => "created"
        match '/linked' => 'users#linked', :as => "linked"
      end
    end
  end

  namespace :admin do
    devise_for :users
    root :to => 'base#index'
    resources :categories
    resources :petitions do
      resources :timelines
    end
    resources :tags
    resources :users
  end

end

app/views/admin/sidebar/_admin_menu.html.slim
= link_to "#", :class => 'visible-phone' do
  i.icon.icon-user
  span Dashboard
ul
  li
    = link_to "連署分類管理", admin_categories_path
  li
    = link_to "連署管理", admin_petitions_path
  li
    = link_to "tag 管理", admin_tags_path
  li
    = link_to "會員管理", admin_users_path
  li
    li.submenu
      a href="#"
        i.icon.icon-user
        span 下拉式選單
      ul
        li
          a.active href="#" AAA
        li
          a href="#" BBB
        li.last
          a href="#" CCC