config/routes.rb
require 'sidekiq/web'

CompaignTw::Application.routes.draw do

  sidekiq_constraints = lambda{ |req| req.env['warden'].authenticate!({ :scope => :user }) }
  constraints sidekiq_constraints do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/users/auth/:provider/callback', :to => "users/omniauth_callbacks#callback"
  match '/users/auth/failure' => "users/omniauth_callbacks#failure", :as => :auth_failure

  Setting.providers.each do |provider|
    match "/users/auth/#{provider}", :as => "user_auth_#{provider}"
  end
  devise_for :users

  root :to => 'categories#index'
  resources :categories
  resources :petitions do
    resources :timelines
    post :sign, :on => :member
    get :dashboard, :on => :member
    resources :comments, :only => [ :index, :create ]
    resources :petition_mail, :only => [ :create ]
  end
  resources :users do
    resources :petitions do
      collection do
        match '/created' => 'users#created', :as => "created"
        match '/linked' => 'users#linked', :as => "linked"
      end
    end
  end

  namespace :admin do
    devise_for :users
    root :to => 'base#index'
    resources :categories
    resources :petitions do
      resources :timelines
    end
    resources :tags
    resources :users
  end

end

app/views/partials/_flash.html.slim
- flash.each do |k, message|
  div class="alert-#{k}"
    = message

app/views/partials/_footer.html.slim
.footer
  .action
    = render_new_petition_link :class => "post-btn btn btn-action"
  .container
    .row
      .footer-item-group
        h3.footer-item-title 連署分類
        ul.footer-item-list
          - @categories.each do |category|
            li
              = link_to category.name, "#"
      .footer-item-group
        .footer-item
          h3.footer-item-title 關於我們
          p.footer-item-content = "# TODO 待補"
          a.mail-to herf="" 聯繫我們
    .row
      .footer-item-group
        h3.footer-item-title 其他服務
        ul.footer-web-guide
          li: a href="" Blog
          li: a href="" 教學
          li: a href="" Privacy
          li: a href="" Guildline
          li: a href="" Bug Report
      .footer-item-group.footer-item-group-last
        h3.footer-item-title 贊助廠商
        / ul.footer-social-link-group
        /   - 8.times do
        /     li.social-link: a href=""= image_tag lorem_image("96x32&text=logo")

    / .copyright © 2013, Cange. All Rights Reserved.

app/views/partials/_header.html.slim
.header
  .header-container
    .mobile-menu.dropdown
      button.dropdown-btn.menu-btn data-toggle="dropdown"
        .menu-btn-bar
        .menu-btn-bar
        .menu-btn-bar
      ul.dropdown-menu role="menu" aria-labelledby="dLabel"
        li = render_new_petition_link
        li = link_to "連署列表", petitions_path
    h1.logo: a href="/" 台灣連署平台
    ul.main-nav.hidden-mobile
      li = render_new_petition_link
      li = link_to "連署列表", petitions_path



    ul.header-user-toolbar
      li.header-user-tool.dropdown.search.hidden-desktop
        a.dropdown-btn.header-user-tool-btn data-toggle="dropdown" href="#": i.icon-search
        .dropdown-menu
          form.search-bar
            input#search type="text" placeholder="Search"
            button.icon-search type="submit"
      / li.header-user-tool
      /   a.login-btn.header-user-tool-btn href="#sign-up" data-toggle="modal" Sign in

      - if user_signed_in?
        li.header-user-tool.dropdown.user-account
          a.dropdown-btn.header-user-tool-btn.hidden-desktop data-toggle="dropdown" href="#": i.icon-user
          a.dropdown-btn.header-user-tool-btn.hidden-mobile data-toggle="dropdown" href="#"
            = image_tag current_user.pic_url(24)
            span.dropdown-title= current_user.name
          ul.dropdown-menu.pull-right role="menu" aria-labelledby="dLabel"
            li = link_to "我發起的", created_user_petitions_path(current_user.id)
            li = link_to "我參與的", linked_user_petitions_path(current_user.id)
            li: a href="/user" 我的資料
            li.dropdown-menu-list-divider
            li
              = link_to "Sign out", destroy_user_session_path, :method => :delete
    form.search-bar.hidden-mobile
      input#search type="text" placeholder="Search"
      button.icon-search type="submit"

app/views/partials/_modal-group.html.slim
= render :partial => "partials/sign-up"
- if user_signed_in?
  = render :partial => "petitions/form"

app/views/partials/_sign-up.html.slim
.modal.fade#sign-up.sign-up tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  .modal-wrapper
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" ×
        .modal-title 登入
        .modal-sub-title.hidden-phone 使用第三方註冊與登入
      .modal-body
        .sign-up-btn-group
          = link_to "Facebook", user_auth_facebook_path, :class => :btn, :type => :button
          = link_to "Google", user_auth_google_oauth2_path, :class => :btn, :type => :button
          button.btn Yahoo! # TODO
      .modal-footer
        .user-term
          a href="" 使用者條款
          span 與
          a href="" 隱私條款