config/routes.rb
require 'sidekiq/web'

CompaignTw::Application.routes.draw do

  sidekiq_constraints = lambda{ |req| req.env['warden'].authenticate!({ :scope => :user }) }
  constraints sidekiq_constraints do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/users/auth/:provider/callback', :to => "users/omniauth_callbacks#callback"
  match '/users/auth/failure' => "users/omniauth_callbacks#failure", :as => :auth_failure

  Setting.providers.each do |provider|
    match "/users/auth/#{provider}", :as => "user_auth_#{provider}"
  end
  devise_for :users

  root :to => 'categories#index'
  resources :categories
  resources :petitions do
    resources :timelines
    post :sign, :on => :member
    get :dashboard, :on => :member
    resources :comments, :only => [ :index, :create ]
    resources :petition_mail, :only => [ :create ]
  end
  resources :users do
    resources :petitions do
      collection do
        match '/created' => 'users#created', :as => "created"
        match '/linked' => 'users#linked', :as => "linked"
      end
    end
  end

  namespace :admin do
    devise_for :users
    root :to => 'base#index'
    resources :categories
    resources :petitions do
      resources :timelines
    end
    resources :tags
    resources :users
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  before_filter :find_tag
  before_filter :except => :index do
    add_crumb("所有 tag", admin_tags_url)
  end

  def index
    @tags = Tag.scoped
    @admin_page_title = "所有 tag"
    add_crumb(@admin_page_title, "#")
  end

  def new
    @admin_page_title = "新增 tag"
    add_crumb(@admin_page_title, "#")
  end

  def create
    if @tag.save
      redirect_to admin_tags_path, :flash => { :success => "已新增" }
    else
      flash[:error] = @tag.errors.full_messages
      render :new
    end
  end

  def edit
    @admin_page_title = "編輯 tag - #{@tag.name}"
    add_crumb(@admin_page_title, "#")
  end

  def update
    if @tag.update_attributes params[:tag]
      redirect_to admin_tags_path, :flash => { :success => "已更新" }
    else
      flash[:error] = @tag.errors.full_messages
      render :edit
    end
  end

  def destroy
    @tag.destroy
    redirect_to admin_tags_path, :flash => { :success => "已刪除" }
  end

  private

  def find_tag
    @tag = params[:id] ? Tag.find(params[:id]) : Tag.new(params[:tag])
  end
end

app/views/admin/tags/_form.html.slim
= f.input :name, :label => "tag 名稱"

.form-actions
  = f.submit :value => "送出", :disable_with => "送出中", :class => "btn btn-primary"
  = link_to "取消", admin_tags_url, :class => "btn"

app/views/admin/tags/edit.html.slim
.span12
  = simple_form_for @tag, :url => admin_tag_path(@tag), :wrapper => :admin, :html => { :class => "form-horizontal" } do |f|
    = render :partial => "form", :locals => { :f => f }

app/views/admin/tags/index.html.slim
- content_for :btns do
  = link_to "新增 tag", new_admin_tag_path, :class => "btn btn-primary"

table.table.table-bordered.table-striped.table-hover
  thead
    tr
      th 
      th tag 名稱
      th 
  tbody
    - @tags.each do |tag|
      tr
        td
          = tag.id
        td
          = tag.name
        td
          = link_to "編輯 tag", edit_admin_tag_path(tag), :class => "btn btn-small btn-info"
          = link_to "刪除 tag", admin_tag_path(tag), :method => :delete, :class => "btn btn-small", :confirm => "確定要刪除 tag - #{tag.name} 嗎？"

app/views/admin/tags/new.html.slim
.span12
  = simple_form_for @tag, :url => admin_tags_path, :wrapper => :admin, :html => { :class => "form-horizontal" } do |f|
    = render :partial => "form", :locals => { :f => f }