config/routes.rb
require 'sidekiq/web'

CompaignTw::Application.routes.draw do

  sidekiq_constraints = lambda{ |req| req.env['warden'].authenticate!({ :scope => :user }) }
  constraints sidekiq_constraints do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '/users/auth/:provider/callback', :to => "users/omniauth_callbacks#callback"
  match '/users/auth/failure' => "users/omniauth_callbacks#failure", :as => :auth_failure

  Setting.providers.each do |provider|
    match "/users/auth/#{provider}", :as => "user_auth_#{provider}"
  end
  devise_for :users

  root :to => 'categories#index'
  resources :categories
  resources :petitions do
    resources :timelines
    post :sign, :on => :member
    get :dashboard, :on => :member
    resources :comments, :only => [ :index, :create ]
    resources :petition_mail, :only => [ :create ]
  end
  resources :users do
    resources :petitions do
      collection do
        match '/created' => 'users#created', :as => "created"
        match '/linked' => 'users#linked', :as => "linked"
      end
    end
  end

  namespace :admin do
    devise_for :users
    root :to => 'base#index'
    resources :categories
    resources :petitions do
      resources :timelines
    end
    resources :tags
    resources :users
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :petitions, :dependent => :nullify
  
  validates_uniqueness_of :name
  validates_presence_of :name

  scope :ordered, order('weight DESC')

  before_destroy :can_delete?

  def can_delete?
    return true if petitions_count == 0
  end
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController  
  before_filter :find_category
  before_filter :except => :index do
    add_crumb("所有連署分類", admin_categories_url)
  end

  def index
    @categories = Category.order("weight DESC")
    @admin_page_title = "所有連署分類"
    add_crumb(@admin_page_title, "#")
  end

  def new
    @admin_page_title = "新增連署分類"
    add_crumb(@admin_page_title, "#")
  end

  def create
    if @category.save
      redirect_to admin_categories_path, :flash => { :success => "已新增" }
    else
      flash[:error] = @category.errors.full_messages
      render :new
    end
  end

  def edit
    @admin_page_title = "編輯連署分類 - #{@category.name}"
    add_crumb(@admin_page_title, "#")
  end

  def update
    if @category.update_attributes params[:category]
      redirect_to admin_categories_path, :flash => { :success => "已更新" }
    else
      flash[:error] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, :flash => { :success => "已刪除" }
  end

  private

  def find_category
    @category = params[:id] ? Category.find(params[:id]) : Category.new(params[:category])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < BaseController

  def index
    @categories = Category.ordered
    @petitions = Petition.scoped
    @petitions_count = Petition.count
    @petition_signs_count = Petition.sum("signs_count")
    render :layout => "application"
  end

end

app/views/admin/categories/_form.html.slim
= f.input :name, :label => "連署分類名稱"
= f.input :weight, :label => "置頂權重", :hint => "數字越大 = 權重越高 = 排序越前面"

.form-actions
  = f.submit :value => "送出", :disable_with => "送出中", :class => "btn btn-primary"
  = link_to "取消", admin_categories_url, :class => "btn"

app/views/admin/categories/edit.html.slim
.span12
  = simple_form_for @category, :url => admin_category_path(@category), :wrapper => :admin, :html => { :class => "form-horizontal" } do |f|
    = render :partial => "form", :locals => { :f => f }

app/views/admin/categories/index.html.slim
- content_for :btns do
  = link_to "新增連署分類", new_admin_category_path, :class => "btn btn-primary"

table.table.table-bordered.table-striped.table-hover
  thead
    tr
      th 
      th 分類名稱
      th 置頂權重
      th 連署數量
      th 
  tbody
    - @categories.each do |category|
      tr
        td
          = category.id
        td
          = category.name
        td
          = category.weight
        td
          = category.petitions_count
        td
          = link_to "編輯連署分類", edit_admin_category_path(category), :class => "btn btn-small btn-info"
          - if category.can_delete?
            = link_to "刪除連署分類", admin_category_path(category), :method => :delete, :class => "btn btn-small", :confirm => "確定要刪除連署分類 - #{category.name} 嗎？"

app/views/admin/categories/new.html.slim
.span12
  = simple_form_for @category, :url => admin_categories_path, :wrapper => :admin, :html => { :class => "form-horizontal" } do |f|
    = render :partial => "form", :locals => { :f => f }